# Site settings
title: > 
  Jason Bash | Omaha, Nebraska
email: 
description: > # this means to ignore newlines until "baseurl:"
  I'm a web developer, project manager. I'm a walker, reader, infrequent photographer, watcher of basketball and October baseball. 
  I try to be a good dad and sometimes I succeed. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.someoneinomaha.com" # the base hostname & protocol for your site
twitter_username: someoneinomaha
github_username:  

# Build settings
markdown: kramdown
